### ISSUE TITLE
Push integration

### ISSUE THREAD

**Issue by davidsowerby** [mcollovati/vertx-vaadin#16]
Ran into a problem with the integration of Push with Krail.  The background is [described here](http://krail.readthedocs.io/en/develop/devguide/devguide-push.html#krail-push-and-vertx)

In brief, in order to change the `PushConfiguration`, which I need to do to create the correct `PushConnection` I end up having to instantiate `SockJSPushConnection` in the UI constructor.

`SockJSPushConnection` uses a reference to the UI.id, not the UI itself, and the id is null at this stage (it is not set until `init()` is called.  But I can't set the id in SockJSPushConnection later, because there is no setter. (I have a workaround from Krail 0.16.8.0 using reflection to set it).

Could `SockJSPushConnection` either use a reference to the UI itself, or provide a setter for the id?  (I'm happy to create a PR if you could tell me which you prefer)

**Comment by mcollovati** [comment]
The main reason to use `UI.id` was to avoid potential serialization problems due to the `UI` reference.
I don't like very much the idea to add a setter for the id, so I think using UI reference will be a better solution.

What do you think about providing a ui id supplier to SockJSPushConnection as an alternative to passing UI reference?
Will this be acceptable from your POV?

```java
interface UIIdSupplier < IntSupplier, Serializable

class SockJSPushConnection(uiIdSupplier: UIIdSupplier) { ... }

class MyUI < UI {
   AtomicInteger uiIdSupplier = new AtomicInteger();
   new SockJsPushConnection(uiIdSupplier::get)

   doInit() {
     ...
     uiIdSupplier.set(this.getUIId())
     ...
   }
}
```

**Comment by davidsowerby** [comment]
I don't quite understand your reservation about holding the UI as a reference - the UI has to be Serializable anyway?  This is what is used in the Atmosphere push connection.

The `UIDSupplier` could be set in the `init()` method - I am doing much the same with my current workaround except I have to do it by reflection.  In practice, however, I am not sure what is gained.   `uiIdSupplier::get` would have to be a Serializable lambda, and encapsulation is not really any different between providing a field setter and a lambda setter.

Or have I missed something?

**Comment by mcollovati** [comment]
You're right; I was too much focused on AtomicInteger as a way to have a serializable lambda :D

I remember I've got some trouble having the UI reference when running in clustered environment; I need to repeat some test.

It would be great if you can open a PR.

**Comment by mcollovati** [comment]
Yes, please, go with UI reference.

Il mar 5 giu 2018, 23:25 David Sowerby <notifications@github.com> ha
scritto:

**Comment by mcollovati** [comment]
Vaadin Flow  introduced a discovery method based on ServiceLoader to setup the PushConnectionFactory and vaadin-flow-sockjs module provides its own implementation.
Closing this issue since there seems to be no interest on vertx-vaadin-8
