### ISSUE TITLE
Push support should be optional

### ISSUE THREAD

**Issue by mcollovati** [mcollovati/vertx-vaadin#21]
At the moment PUSH support is always activated, even if application does not require it.
Push handler should be activated only if the sockjs based PUSH implentation is present on classpath.

**Comment by Dudeplayz** [comment]
It's a good idea. Would it be also possible to stay on the atmosphere stack if sockjs is missing? In the atmosphere documentation vertx is also mentioned as supported. Or does the vaadin atmosphere implementation needs the servlet stack?

**Comment by mcollovati** [comment]
Atmosphere was the first choice, since, as you said, was mentioned as supported. Unfortunately it doesn't work well and there was frequent disconnection. I tried to embed and patch classes but the solution was never reliable. So I decided to move to a sockjs implementation due to its native support on vertx, and it seems to me to be a good solution.

**Comment by mcollovati** [comment]
Feature released in vertx-vaadin-flow:14.0.10 and vertx-vaadin-flow:14.1.0
