### ISSUE TITLE
Missing vertx-vaadin-root from repository

### ISSUE THREAD

**Issue by diamondq** [mcollovati/vertx-vaadin#23]
It looks like you updated the reference to vertx-vaadin-root from 1.0.0 to 1.0.0v8v13. Unfortunately, the 1.0.0v8v13 version wasn't pushed to BinTray or Central. Could you push those? I know I can build it locally to get the files into my repository, but not as reproducible. Cheers

**Comment by mcollovati** [comment]
Thanks for pointing this out. 
Root poms has been deployed on bintray and also synced on maven central.

Feel free to reopen this issue is something doesn't work as expected
