### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by diamondq** [mcollovati/vertx-vaadin#24]
The VertxVaadin initSockJS method uses the java.nio.Paths class to attempt to assemble a path. Unfortunately, it assembles a "/" with a "*". Under Windows, * is not a valid character, and as such, the Paths.get() call fails with an illegal character exception.

I think that it'd be better to just assemble the path using Strings to make it work on both Windows and Linux-based environments.

**Comment by mcollovati** [comment]
Thanks for suggestion; I'll fix and also check for other potential wrong usages of `Paths.get(...)`

**Comment by mcollovati** [comment]
Fixed on vaadin-13 branch; snapshot published on bintray, but not yet released on maven central.

Change may also be backported on other branches

**Comment by mcollovati** [comment]
Published vertx-vaadin-flow 13.0.1 that fixes the issue
