### ISSUE TITLE
Vaadin 14.1.x has missing theme

### ISSUE THREAD

**Issue by Dudeplayz** [mcollovati/vertx-vaadin#32]
Vaadin-Vertx-Flow is not working with Vaadin 14.1.x. The theming is missing completely. If I change the version back to 14.0.x everything works. I've tested it with different projects, also with the vertx-flow-example project.

**Comment by mcollovati** [comment]
Thanks for reporting, I'll take a look at this as soon as possible

**Comment by mcollovati** [comment]
Ok the problem was on the set of annotated classes supplied to `DevModeInitializer`; vertx-vaadin was scanning for too few annotation.

Just published a snapshot version (14.1.0-SNAPSHOT) on https://oss.jfrog.org/artifactory/oss-snapshot-local if you want to give it a try

**Comment by Dudeplayz** [comment]
I've tried it with vertx-vaadin-samples and an additional project. It worked immediately! So I think it should work with any other project too. Great job and thanks for the fast response! 👍

**Comment by mcollovati** [comment]
Thanks for feedback. I will complete work on #33 and the cut a release
