### ISSUE TITLE
Support Vertx 3.8.x and 4.x.x, Issue with SockJSHandler

### ISSUE THREAD

**Issue by Dudeplayz** [mcollovati/vertx-vaadin#33]
A dependency upgrade to vertx 3.8.x and 4.x.x is not possible due to the change of the method signature of `(SockJSHandler -> Router) SockJSHandler.socketHandler(Handler<SockJSSocket> handler)`.

https://github.com/vert-x3/vertx-web/blob/4711942d7801d4dab54a46b256cb72edc908cd58/vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/SockJSHandler.java#L68

First occurred on:
https://github.com/mcollovati/vertx-vaadin/blob/a03b8b0d33174b2e4af5337ed6b65a5e29bfe8e7/vertx-vaadin-flow-parent/vertx-vaadin-flow/src/main/java/com/github/mcollovati/vertx/vaadin/sockjs/communication/SockJSPushHandler.java#L167
It looks like the library only needs to be recompiled, but I am not sure if there are any side effects. The router which is returned is meant to be registered at a parent router.

I think the upgrade should be applied to the Vaadin 14 version too because it's an LTS release.

**Comment by mcollovati** [comment]
The mentioned change has been introduced with vertx 3.8.3, so I think i will ignore versions from 3.8.0 to 3.8.2.
There will be a vertx-vaadin-flow:14.0.X and a vertx-vaadin-flow:14.1 based on vertx 3.8.3+

**Comment by Dudeplayz** [comment]
This sounds great 👍

**Comment by mcollovati** [comment]
Published artifacts:
vertx-vaadin-flow:14.0.10 for Vaadin 14.0.x and Vert.x 3.8.3+
vertx-vaadin-flow:14.1.0 for Vaadin 14.1.x and Vert.x 3.8.3+

**Comment by Dudeplayz** [comment]
Again thanks for fast fixing. When will it be available on Maven?
