### ISSUE TITLE
Http port on startup not displayed correctly

### ISSUE THREAD

**Issue by Dudeplayz** [mcollovati/vertx-vaadin#37]
Hi,
I again :D

There is a little bug in the startup routine. The http port is not displayed correctly:
`[vert.x-eventloop-thread-0] INFO com.github.mcollovati.vertx.vaadin.VaadinVerticle - Started vaadin verticle vertx.UIVerticle on port io.vertx.core.http.impl.HttpServerImpl@33e0a022`

**Comment by mcollovati** [comment]
Thanks for reporting, will fix ASAP
