### ISSUE TITLE
Create branch for vaadin 10 support

### ISSUE THREAD

**Issue by mcollovati** [mcollovati/vertx-vaadin#4]

**Comment by mcollovati** [comment]
Instead of a separated branch consider creating three separated projects:
- vertx-vaadin-common: vertx related components, common code, vertx-vaadin abstraction 
- vertx-vaadin8: vaadin 8 adapter
- vertx-vaadin10: vaadin 10 adapter

At every release all three artifacts will be produced and deployed with the same version.
Mostly depends on how many changes are required in router configuration for Vaadin 10

**Comment by davidsowerby** [comment]
Having three libraries is a good idea I think.  I'm not sure about trying to keep the versions the same ... I understand the desire to do that, but the Vaadin 10 branch will change more frequently than the others - so you will be changing the version of vertx-vaadin8 and vertx-vaadin-common when nothing has actually changed in them.  Dependency management (Maven / Gradle) will take care of differing version numbers.

**Comment by mcollovati** [comment]
I think you're right; in this case having separated version would be a better choice.

My thought was that having a single version would simplify the automation of deployment process; but for now I think I can do it manually :smile:

**Comment by petarov** [comment]
@mcollovati Is this still on your TODO list? I'd love to see a vaadin10 support. 😉

**Comment by mcollovati** [comment]
@petarov This is definitely on TODO list 

I already have a local branch for Vaadin 10, but I had some troubles with the integration, and then I didn't had enough time to dedicate to this project.

I hope to start working again on it in the next months

**Comment by petarov** [comment]
Super cool! I'll play with it this week and get back to you.

**Comment by mcollovati** [comment]
Great, thanks. Here's a link to vaadin sample app running on vertx 

https://vertx-vaadin10-example.herokuapp.com/

**Comment by mcollovati** [comment]
Stuff for Vaadin flow merged into master
