### ISSUE TITLE
Missing grid footers and headers

### ISSUE THREAD

**Issue by Dudeplayz** [mcollovati/vertx-vaadin#40]
Hi,
I've created recently an [issue in the vaadin-grid-flow project](https://github.com/vaadin/vaadin-grid-flow/issues/972).
I thought it is generally vaadin related and was already wondering why nobody else has reported this breaking issue before. So I tried it today with a clean vaadin-jetty project and it worked as expected.
Can you check if this is maybe vertx-vaadin related?

**Comment by mcollovati** [comment]
That's weird. It works when i build the production package, but it doesn't in dev-mode.

In production mode the generated `target/frontend/generated-flow-imports.js` contains a reference to ``, whereas in dev-mode it is not present.

**Comment by mcollovati** [comment]
It was a problem on vertx-vaadin class scanning.
`com.vaadin.flow.component.grid.ColumnGroup` has package protected visibility, so it was not added to DevModeInitializer ClassFinder.

I've just published a fixed version of vertx-vaadin 14.2.0-SNAPSHOT.

@Dudeplayz let me know if it works also for you.

**Comment by mcollovati** [comment]
And, as usually, thank you very much for reporting.

**Comment by Dudeplayz** [comment]
It seems to work. Thanks for the fast fix. So I can close the issue in the grid component.
