### ISSUE TITLE
Unnecessary call to ServletFileUpload in StreamReceiverHandler?

### ISSUE THREAD

**Issue by jhult** [mcollovati/vertx-vaadin#42]
In [StreamReceiverHandler](/mcollovati/vertx-vaadin/blob/master/vertx-vaadin-flow-parent/vertx-vaadin-flow/src/main/java/com/github/mcollovati/vertx/vaadin/communication/StreamReceiverHandler.java#L171), on line 171, there is a call to `org.apache.commons.fileupload.servlet.ServletFileUpload` that seems to never be utilized. This is likely a relic from Vaadin Flow that can be removed.

**Comment by mcollovati** [comment]
Hi, thanks for reporting.
You're right, the call should  be removed.
