### ISSUE TITLE
Vaadin 14 and gradle

### ISSUE THREAD

**Issue by mkit** [mcollovati/vertx-vaadin#46]
Is there an example of using vertx-vaadin with vaadin 14 and gradle? There is a sample project in your repo but not sure if it is fully functional.

**Comment by mcollovati** [comment]
Actually there's no working example using gradle.
There was an issue about gradle build on the samples repo, but i is outdated.

I'm not a gradle user, but I think that adding the [vertx-gradle-plugin](https://github.com/jponge/vertx-gradle-plugin) to an existing gradle project should be enough to run an application or to build an executable jar.

**Comment by mkit** [comment]
Thanks a lot for your reply.
