### ISSUE TITLE
Extra addons

### ISSUE THREAD

**Issue by mkit** [mcollovati/vertx-vaadin#47]
Is there a way to introduce add-ons from the vaadin directory. I would like to add support for maps but not sure how to do that in vertx-vaadin. I know there is a separate widgetset. Is there a way to extend it?

Thank you in advance for your reply.

**Comment by mcollovati** [comment]
If you are on vaadin 14 you can use compatible addons from directory; there's no widgetset anymore for components.
GWT is now used  for the low level communication stuff between client and server, but not for components.
Beware that you can have troubles if the addon has explicit referencs  on servlet stuff (eg VaadinServletRequest).

In general a Vaadin application written to run into a servlet container should work without changes with vertx-vaadin.
However, if the application uses PUSH you should exclude **flow-push** and **flow-client** and depend on **vaadin-flow-sockjs** module.

See https://github.com/mcollovati/vertx-vaadin/tree/master/vertx-vaadin-flow-parent/vertx-vaadin-flow/README.md for some detail.

**Comment by mkit** [comment]
Thanks a lot for your reply. Is it possible to use vaadin-vertx 8 with add-ons? 
Also, if you were to start a new project would you go with vaadin 8 or 14? Do you think vaadin 14 is mature enough?
In my scenario I need to use a map component. I can use one of the available in jQuery. Do you think there is a good support for external JavaScript components (with callbacks support) in vaadin-vertx 14?

**Comment by mcollovati** [comment]
You can use vertx-vaadin 8 with addon, but in this case may have to recompile the widgetset ( (as you said).
For a new project I would definitively got with Vaadin 14; Vaadin 8 maintenance will end on February 2022;
and IMO integrating external components is much easier with Vaadin 14, especially web-components (https://vaadin.com/docs/v14/flow/web-components/integrating-a-web-component.html).
Furthermore Element javascript api now allows also to obtain return value of function executed on client side
(https://vaadin.com/docs/v14/flow/element-api/client-server-rpc.html#return-values)

Also for map it seems there are several addons for Vaddin 14 on directory

**Comment by mkit** [comment]
Thank you very much that helps a lot.
Two last things, 
1. Is it possible to compile the vaadin-vertx 14 (with my custom views and add-ons) into a single JAR and use it in another project?
2. Regarding "If you are on vaadin 14 you can use compatible addons from directory", Is there some extra steps (like pre-compilation) I need to take to be able to use those add-ons?

**Comment by mcollovati** [comment]
1. I think there should be no problem creating an uber jar with vertx-vaadin, addons and your code, but I can't see how this can be better than simply depend on them separately on the other project.
2. Only extra step should be configure maven or gradle vaadin plugin (see https://vaadin.com/docs/flow/getting-started/getting-started-gradle.html)

**Comment by mkit** [comment]
Thanks.
Regarding 2. vaadin-vertx already has it configured, am I right here? I mean the maven plugin. As such, if I decide to go with maven setup (instead of gradle) I don't need to do anything. Is that correct?

**Comment by mcollovati** [comment]
vertx-vaadin is just a library. You should configure the build tool (maven or gradle) on your own.

Getting started section of [REAMDE](https://github.com/mcollovati/vertx-vaadin/blob/master/vertx-vaadin-flow-parent/vertx-vaadin-flow/README.md) may help you to setup a simple project with maven..

**Comment by mcollovati** [comment]
I'm going to close this issue. If you need further help we can get in touch in then newly created [Gitter room](https://gitter.im/vertx-vaadin/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link)
