### ISSUE TITLE
Preliminary investigation to support vert.x 4.x 

### ISSUE THREAD

**Issue by mcollovati** [mcollovati/vertx-vaadin#49]

**Comment by Dudeplayz** [comment]
If I am right, then is `vert.x 3.9.5` compatible with `4.0`. So if you upgrade to 3.9.5 it should also run under 4.0.

**Comment by mcollovati** [comment]
Thanks for the hint. I'll follow your suggestion and upgrade to 3.9.5 and then do some test with vert.x 4.x at runtime only

**Comment by mcollovati** [comment]
Upgrade to Vert.x 4.x is completed on branch vaadin-14.2, but not yet ported on development

**Comment by mcollovati** [comment]
Support for vertx 4 is now also on development branch
