### ISSUE TITLE
Migrate from Bintray

### ISSUE THREAD

**Issue by mcollovati** [mcollovati/vertx-vaadin#51]
Currently artifacts are deployed on Bitray and then synced  to Maven central.
Since Bintray will be sunsetted as of May 2021, consider migrate to JFrog (free plan) or directly publish on Maven central.

For vertx-vaadin-sockjs classifiers perhaps we can use Github packages.

**Comment by Dudeplayz** [comment]
I found this [article](http://bjansen.github.io/java/2021/02/03/deploying-to-maven-central-using-github-actions.html), maybe it helps. Are there any reasons to not publish directly to maven?

**Comment by mcollovati** [comment]
Thanks for the link.
Regarding publishing directly on Maven central, at the moment the main problem may be with vertx-vaadin-sockjs classifiers, because, if I'm not wrong, it is not possible to deploy additional artifacts for an existing version.

**Comment by mcollovati** [comment]
Not to mention that with bintray you don't need to do all the signing stuff on your own

**Comment by mcollovati** [comment]
Deploy for next versions will be published on JFrog
https://mcollovati.jfrog.io/
