### ISSUE TITLE
Setup Github Actions workflow to deploy vaadin-flow-sockjs classifiers

### ISSUE THREAD

**Issue by mcollovati** [mcollovati/vertx-vaadin#52]
Setup a workflow that builld **vaadin-flow-sockjs** jar for specific Vaadin versions and deploy them to a public remote repository.
To build and deploy we can use the existing script **build_flow_widgetsets.sh** in tools directory.
Remote repository may be JFrog, since JCenter and Bintray will no more work after May 2021.
The workflow may be scheduled once per week, but it should also be possible to launch it manually.

**Comment by Dudeplayz** [comment]
Is there a reason to use a script? I tried this 1 hour ago in my fork and deploy it to GitHub packages. But it fails because it can't find the parent pom. I'm not familiar with CircleCI, is there anything to consider?

**Comment by mcollovati** [comment]
A `./mvnw -N install` must be launched before the script in order to install the parent pom.

The script performs the following tasks:

1. check the Vaadin version in use from the root pom (property *vaadin.platform.version*)
2. get the list of "compatible" Vaadin version by querying search.maven.org
3. for each Vaadin version detect the corresponding *flow-client* version
4. for each distinct *flow-clienté version build and deploy *vaadin-flow-sockjs* artifact with a classifier reflecting Vaadin version

If you have a better solution in mind, I'll be glad to discuss and potentially refactor the process.

**Comment by Dudeplayz** [comment]
I was trying it with a maven docker image. I haven't known, that the maven wrapper is doing some more stuff.
I can't find the script which describes your workflow, can you supply a ref?
For the moment I don't have another workflow in mind. I think your workflow has been proven as stable.

**Comment by mcollovati** [comment]
Perhaps we had a misunderstanding: I was talking about the script **build_flow_widgetsets.sh** in the **tools** directory, not about maven wrapper.
The `./mvnw -N install` command should be launche before `./tools/build_flow_widgetsets.sh` because the script only build the **vaadin-flow-sockjs** module

**Comment by mcollovati** [comment]
BTW I added a workflow on spikes/github-actions branch,if you want to have a look and give some advice.

**Comment by Dudeplayz** [comment]
Ah ok, this was the file I was skipping, cause I thought that there is nothing important. I will take a look again.
I saw the branch, there are just tests at the moment?

**Comment by mcollovati** [comment]
Yes, I'm doing some workflow test on that branch, and it seems to work as expected.
I will then squash and merge the changes into vaadin-18 branch, scheduling the workflow once a week.
If all works fine next step will be porting the workflow on all other release branches

**Comment by Dudeplayz** [comment]
Sounds great 👍

**Comment by mcollovati** [comment]
Scheduled workflow is running every night for test. If no problems arise the schedule will change to run once a week.

**Comment by mcollovati** [comment]
The **build_flow_widgetsets.sh** has been improved to only build classifiers not yet deployed on JFrog; this means that the workflow can have a daily schedule, since most of times it will complete in short time without building anything.

**Comment by Dudeplayz** [comment]
This is even better. This allows updating one day after an update is published.

**Comment by Dudeplayz** [comment]
Is it right to name it `build_flow_widgetsets.sh`, even if there are actually no widget sets anymore?

**Comment by mcollovati** [comment]
The widgetset (here intended as GWT compiled resources) is already present, but it is limited to the communication stack.

I'm going to close this issue since the workflow seem to work correctly
