### ISSUE TITLE
Exceptions in VaadinVerticle startup can disappear

### ISSUE THREAD

**Issue by Dudeplayz** [mcollovati/vertx-vaadin#61]
If in the following code an exception is thrown, it can disappear because it is not bubbled up.
https://github.com/mcollovati/vertx-vaadin/blob/7a89b11f0fa005ca83c841371bc3dff2c3f3bc67/vertx-vaadin-flow-parent/vertx-vaadin-flow/src/main/java/com/github/mcollovati/vertx/vaadin/VaadinVerticle.java#L228-L243

The code to bubble up the exception in the future chain is in line 238. So if an exception is thrown before (in my case in line 230), then the catch block is called with failing the future. But the `onComplete` for the "parent" future isn't registered yet and is never called. So in my case, the complete initialization of the VaadinVerticle never finishes and the exception is never logged or thrown.

This is the only place where I discovered this behavior, maybe something similar can happen somewhere else. Should be checked.

**Comment by mcollovati** [comment]
Fixed by 06a763eef8e4849bb5b79fa5f9c22b1448427bab
