### ISSUE TITLE
dev-tools connection fails because of wrong path

### ISSUE THREAD

**Issue by Dudeplayz** [mcollovati/vertx-vaadin#74]
<img width="720" alt="image" src="https://github.com/mcollovati/vertx-vaadin/assets/15174076/09e86d32-c907-4c36-8537-7e32c687a0e6">

**Comment by mcollovati** [comment]
Fixed by 5e4967b3075f40d95793aa08fb7a9b04025eddb4 and released with [flow-23.3.1](https://github.com/mcollovati/vertx-vaadin/releases/tag/flow-23.3.1)
