### ISSUE TITLE
Vaadin 24 support

### ISSUE THREAD

**Issue by arouel** [mcollovati/vertx-vaadin#76]
Are there any plans to support Vaadin 24?

**Comment by mcollovati** [comment]
Hi, thanks for the interest in the project!

Support for Vaadin 24 is on the to-do list, but development has not yet started.
It will require a huge refactoring, so I currently do not have an indication of when it could be ready.

**Comment by mcollovati** [comment]
The development branch is now updated to Vaadin 24.3.
A first alpha version (24.3.0-alpha1) is available on maven central.

@arouel I'll close the issue. If you have any questions, please comment here or create a new ticket.
