### ISSUE TITLE
@Widgetset annotation

### ISSUE THREAD

**Issue by davidsowerby** [mcollovati/vertx-vaadin#8]
I think the @Widgetset annotation should be on the Verticle, rather than the UI - there will only be one of them, but there could be multiple UI classes

**Comment by mcollovati** [comment]
After looking back to the code I remembered that to be consistent with Vaadin configuration modes there are three ways to configure widgetset:

- `@WidgetSet` annotation on UI
- `@VaadinServletConfiguration.widgetset()` on VaadinVerticle subclass
- `vaadin.widgetset` key in json configuration file

Maybe it would be better to replace `@VaadinServletConfiguration` with a new annotation specific for vertx environment, eg `@VaadinVertxConfiguration`

**Comment by mcollovati** [comment]
This should absolutely be documented

**Comment by davidsowerby** [comment]
Good point, it would be better to remain as consistent as possible with standard Vaadin.

I guess the Verticle is roughly equivalent to a servlet, would `@VaadinVerticleConfiguration` perhaps be better than `@VaadinVertxConfiguration` ?  (I'm not completely sure!)

**Comment by mcollovati** [comment]
`@VaadinVerticleConfiguration` is indeed a better name

**Comment by mcollovati** [comment]
Closing issue because it seems there's no interest on vertx-vaadin-8 and Vaadin Flow has abandoned GWT for UI components
